name:                pluto-lang
version:             0.1.0.0
github:              "Theomund/pluto-lang"
license:             MIT
author:              "Gregory Shuck"
maintainer:          "gregoryshuck96@gmail.com"
copyright:           "2019 Gregory Shuck"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Theomund/pluto-lang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- hspec
- hspec-megaparsec
- lens
- containers
- llvm-hs
- llvm-hs-pure
- bytestring
- filepath

library:
  source-dirs: src

executables:
  pluto-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pluto-lang

tests:
  pluto-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pluto-lang
